version: 0.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore EvolveVideos\EvolveVideos.sln
build:
  project: EvolveVideos\EvolveVideos.sln
  verbosity: minimal
cache:
  - packages -> **\packages.config